name: Kali Linux Remote Desktop

on:
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Add Kali Linux repository
      run: |
        # Add the Kali Linux repository
        echo "deb http://http.kali.org/kali kali-rolling main non-free contrib" | sudo tee /etc/apt/sources.list.d/kali.list
        sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys ED444FF07D8D0BF6
        sudo apt-get update
        
    - name: Install Kali Linux
      run: |
        # Install Kali Linux desktop
        sudo apt-get install -y kali-linux-default-desktop
        
    - name: Start Kali Linux desktop
      run: |
        # Set the username and password
        USERNAME="runneradmin"
        PASSWORD="Umair@030200"
        
        # Start the Kali Linux desktop
        xvfb-run --auto-servernum --server-num=1 --server-args="-ac" \
        /usr/bin/startxfce4 &
        
        # Expose the desktop via ngrok
        ngrok http 3389 --region=us --log=stdout > ngrok_url.txt
        
    - name: Get ngrok URL
      id: ngrok
      run: |
        # Read the ngrok URL from the file
        NGROK_URL=$(cat ngrok_url.txt | grep -o -E "https://[a-z0-9]+\.ngrok.io")
        echo "::set-output name=url::$NGROK_URL"
        
    - name: Print instructions
      run: |
        echo "To access the remote Kali Linux desktop, follow these steps:"
        echo "1. Open your web browser and go to the following URL:"
        echo "${{ steps.ngrok.outputs.url }}"
        echo "2. When prompted, enter the username: $USERNAME"
        echo "3. When prompted, enter the password: $PASSWORD"
        echo "You should now have access to the remote Kali Linux desktop!"
