name: Ubuntu Remote Desktop (VNC)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Install and Configure VNC
      run: |
        sudo apt-get update
        sudo apt-get install -y xfce4 xfce4-goodies tightvncserver
        mkdir -p ~/.vnc
        echo "Umair@030200" | vncpasswd -f > ~/.vnc/passwd
        chmod 600 ~/.vnc/passwd
        vncserver :1
        vncserver -kill :1
        echo "#!/bin/bash" > ~/.vnc/xstartup
        echo "xrdb $HOME/.Xresources" >> ~/.vnc/xstartup
        echo "startxfce4 &" >> ~/.vnc/xstartup
        chmod +x ~/.vnc/xstartup
        vncserver :1 -geometry 1920x1080 -depth 24
        
    - name: Expose VNC
      id: expose-vnc
      run: |
        VNC_HOST=$(curl -s https://api.ipify.org)
        VNC_PORT=5901
        VNC_USERNAME=runneradmin
        VNC_PASSWORD=Umair@030200
        
        echo "VNC_HOST=$VNC_HOST" >> $GITHUB_OUTPUT
        echo "VNC_PORT=$VNC_PORT" >> $GITHUB_OUTPUT
        echo "VNC_USERNAME=$VNC_USERNAME" >> $GITHUB_OUTPUT
        echo "VNC_PASSWORD=$VNC_PASSWORD" >> $GITHUB_OUTPUT
        
    - name: Display Connection Details
      run: |
        echo "You can connect to the Ubuntu remote desktop using the following details:"
        echo "VNC Host: ${{ steps.expose-vnc.outputs.VNC_HOST }}"
        echo "VNC Port: ${{ steps.expose-vnc.outputs.VNC_PORT }}"
        echo "VNC Username: ${{ steps.expose-vnc.outputs.VNC_USERNAME }}"
        echo "VNC Password: ${{ steps.expose-vnc.outputs.VNC_PASSWORD }}"
