name: Ubuntu Remote Desktop (VNC)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Install VNC and Desktop Environment
      run: |
        sudo apt-get update
        sudo apt-get install -y xfce4 xfce4-goodies tightvncserver jq curl
        mkdir -p ~/.vnc
        echo "Umair@030200" | vncpasswd -f > ~/.vnc/passwd
        chmod 600 ~/.vnc/passwd
        vncserver :1
        vncserver -kill :1
        echo "#!/bin/bash\nxrdb $HOME/.Xresources\nstartxfce4 &" > ~/.vnc/xstartup
        chmod +x ~/.vnc/xstartup
        vncserver :1 -geometry 1280x800 -depth 24
    
    - name: Get Public IP Address
      id: get-ip
      run: |
        IP_ADDRESS=$(curl -s https://api.ipify.org)
        echo "IP_ADDRESS=${IP_ADDRESS}" >> $GITHUB_ENV
        
    - name: Display Connection Details
      run: |
        echo "You can connect to the Ubuntu remote desktop using the following details:"
        echo "VNC Host: ${{ env.IP_ADDRESS }}:5901"
        echo "VNC Username: runneradmin"
        echo "VNC Password: Umair@030200"
        
    - name: Set VNC Password
      run: |
        echo -e "Umair@030200\nUmair@030200" | sudo passwd runneradmin
