name: Ubuntu Remote Desktop (Guacamole)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Install Guacamole
      run: |
        sudo apt-get update
        sudo apt-get install -y guacamole-client guacamole-server
        sudo systemctl enable guacd
        sudo systemctl start guacd
        
    - name: Expose Guacamole
      run: |
        GUACAMOLE_HOST=$(curl -s https://api.ipify.org)
        GUACAMOLE_PORT=8080
        GUACAMOLE_USERNAME=runneradmin
        GUACAMOLE_PASSWORD=Umair@030200
        
        echo "GUACAMOLE_HOST=$GUACAMOLE_HOST" >> $GITHUB_OUTPUT
        echo "GUACAMOLE_PORT=$GUACAMOLE_PORT" >> $GITHUB_OUTPUT
        echo "GUACAMOLE_USERNAME=$GUACAMOLE_USERNAME" >> $GITHUB_OUTPUT
        echo "GUACAMOLE_PASSWORD=$GUACAMOLE_PASSWORD" >> $GITHUB_OUTPUT
        
    - name: Display Connection Details
      run: |
        echo "You can access the Ubuntu remote desktop using the following URL in your browser:"
        echo "http://${{ steps.expose-guacamole.outputs.GUACAMOLE_HOST }}:${{ steps.expose-guacamole.outputs.GUACAMOLE_PORT }}"
        echo "Username: ${{ steps.expose-guacamole.outputs.GUACAMOLE_USERNAME }}"
        echo "Password: ${{ steps.expose-guacamole.outputs.GUACAMOLE_PASSWORD }}"
