name: Ubuntu Remote Desktop (RDP)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Install RDP
      run: |
        sudo apt-get update
        sudo apt-get install -y xrdp
        sudo systemctl enable xrdp
        sudo systemctl start xrdp
        
    - name: Expose RDP
      id: expose-rdp
      run: |
        RDP_HOST=$(curl -s https://api.ipify.org)
        RDP_PORT=3389
        RDP_USERNAME=runneradmin
        RDP_PASSWORD=$(openssl rand -hex 8)
        
        echo "RDP_HOST=$RDP_HOST" >> $GITHUB_OUTPUT
        echo "RDP_PORT=$RDP_PORT" >> $GITHUB_OUTPUT
        echo "RDP_USERNAME=$RDP_USERNAME" >> $GITHUB_OUTPUT
        echo "RDP_PASSWORD=$RDP_PASSWORD" >> $GITHUB_OUTPUT
        
    - name: Display Connection Details
      run: |
        echo "You can connect to the Ubuntu remote desktop using the following details:"
        echo "RDP Host: ${{ steps.expose-rdp.outputs.RDP_HOST }}"
        echo "RDP Port: ${{ steps.expose-rdp.outputs.RDP_PORT }}"
        echo "RDP Username: ${{ steps.expose-rdp.outputs.RDP_USERNAME }}"
        echo "RDP Password: ${{ steps.expose-rdp.outputs.RDP_PASSWORD }}"
