name: Ubuntu Remote Desktop (RDP)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Install RDP
      run: |
        sudo apt-get update
        sudo apt-get install -y xrdp xfce4 xfce4-goodies
        sudo systemctl enable xrdp
        sudo systemctl start xrdp
        echo "xfce4-session" > ~/.xsession
        sudo service xrdp restart
    
    - name: Install Ngrok
      run: |
        wget -q -O ngrok.zip https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip
        unzip ngrok.zip
        sudo mv ngrok /usr/local/bin/ngrok
        
    - name: Start Ngrok
      id: start-ngrok
      run: |
        nohup ngrok tcp 3389 --log=stdout &
        sleep 10
        NGROK_URL=$(curl -s localhost:4040/api/tunnels | jq -r .tunnels[0].public_url)
        echo "NGROK_URL=${NGROK_URL}" >> $GITHUB_OUTPUT

    - name: Display Connection Details
      run: |
        echo "You can connect to the Ubuntu remote desktop using the following details:"
        echo "RDP Host: ${{ steps.start-ngrok.outputs.NGROK_URL }}"
        echo "RDP Username: runneradmin"
        echo "RDP Password: Umair@030200"
        
    - name: Set RDP Password
      run: |
        echo -e "Umair@030200\nUmair@030200" | sudo passwd runneradmin
